### ISSUE TITLE
How to use Proxy Scraper on Windows 10

### ISSUE THREAD

**Issue by byomartin** [hendrikbgr/Proxy-Scraper#1]
Great program. It will be hard for non tech people to use the program on Windows 10 so here is the guide
- Open Start and search for Microsoft Store
- Find "python" and install Python 3.10
- Download proxy scraper source code and unzip to any folder
- Open source folder, on the file explorer address bar now type "cmd" to open command line terminal
- Now type "pip install requests-html" to install requests-html module
- Type "pip install aiohttp" to install aiohttp module
- Now type "python3 main.py" the program will start
- Wait till it finishes you will get fresh working proxies

**Comment by hendrikbgr** [comment]
thank you for this. I will add it to the README
